// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"context"
)

const createDestination = `
INSERT INTO destinations (user_id, name, latitude, longitude, radius_m, target_text)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, latitude, longitude, radius_m, target_text, created_at
`

type CreateDestinationParams struct {
	UserID     string  `json:"user_id"`
	Name       string  `json:"name"`
	Latitude   float64 `json:"latitude"`
	Longitude  float64 `json:"longitude"`
	RadiusM    int32   `json:"radius_m"`
	TargetText string  `json:"target_text"`
}

func (q *Queries) CreateDestination(ctx context.Context, arg CreateDestinationParams) (Destination, error) {
	row := q.db.QueryRow(ctx, createDestination,
		arg.UserID, arg.Name, arg.Latitude, arg.Longitude, arg.RadiusM, arg.TargetText,
	)
	var i Destination
	err := row.Scan(&i.ID, &i.UserID, &i.Name, &i.Latitude, &i.Longitude, &i.RadiusM, &i.TargetText, &i.CreatedAt)
	return i, err
}

const listDestinationsByUser = `
SELECT id, user_id, name, latitude, longitude, radius_m, target_text, created_at
FROM destinations WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDestinationsByUser(ctx context.Context, userID string) ([]Destination, error) {
	rows, err := q.db.Query(ctx, listDestinationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Destination
	for rows.Next() {
		var i Destination
		if err := rows.Scan(&i.ID, &i.UserID, &i.Name, &i.Latitude, &i.Longitude, &i.RadiusM, &i.TargetText, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getDestination = `
SELECT id, user_id, name, latitude, longitude, radius_m, target_text, created_at
FROM destinations WHERE id = $1 AND user_id = $2 LIMIT 1
`

func (q *Queries) GetDestination(ctx context.Context, id, userID string) (Destination, error) {
	row := q.db.QueryRow(ctx, getDestination, id, userID)
	var i Destination
	err := row.Scan(&i.ID, &i.UserID, &i.Name, &i.Latitude, &i.Longitude, &i.RadiusM, &i.TargetText, &i.CreatedAt)
	return i, err
}

const deleteDestination = `
DELETE FROM destinations WHERE id = $1 AND user_id = $2
`

func (q *Queries) DeleteDestination(ctx context.Context, id, userID string) error {
	_, err := q.db.Exec(ctx, deleteDestination, id, userID)
	return err
}
