// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"context"
	"time"
)

type DeviceStatus struct {
	ID        string    `json:"id"`
	DeviceID  string    `json:"device_id"`
	Battery   int32     `json:"battery"`
	LidarOk   bool      `json:"lidar_ok"`
	CameraOk  bool      `json:"camera_ok"`
	GpsOk     bool      `json:"gps_ok"`
	NetworkOk bool      `json:"network_ok"`
	CreatedAt time.Time `json:"created_at"`
}

type UpsertDeviceStatusParams struct {
	DeviceID  string `json:"device_id"`
	Battery   int32  `json:"battery"`
	LidarOk   bool   `json:"lidar_ok"`
	CameraOk  bool   `json:"camera_ok"`
	GpsOk     bool   `json:"gps_ok"`
	NetworkOk bool   `json:"network_ok"`
}

const upsertDeviceStatus = `
INSERT INTO device_status (device_id, battery, lidar_ok, camera_ok, gps_ok, network_ok)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, device_id, battery, lidar_ok, camera_ok, gps_ok, network_ok, created_at
`

func (q *Queries) UpsertDeviceStatus(ctx context.Context, arg UpsertDeviceStatusParams) (DeviceStatus, error) {
	row := q.db.QueryRow(ctx, upsertDeviceStatus,
		arg.DeviceID, arg.Battery, arg.LidarOk, arg.CameraOk, arg.GpsOk, arg.NetworkOk,
	)
	var i DeviceStatus
	err := row.Scan(&i.ID, &i.DeviceID, &i.Battery, &i.LidarOk, &i.CameraOk, &i.GpsOk, &i.NetworkOk, &i.CreatedAt)
	return i, err
}

const getLatestDeviceStatus = `
SELECT id, device_id, battery, lidar_ok, camera_ok, gps_ok, network_ok, created_at
FROM device_status WHERE device_id = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestDeviceStatus(ctx context.Context, deviceID string) (DeviceStatus, error) {
	row := q.db.QueryRow(ctx, getLatestDeviceStatus, deviceID)
	var i DeviceStatus
	err := row.Scan(&i.ID, &i.DeviceID, &i.Battery, &i.LidarOk, &i.CameraOk, &i.GpsOk, &i.NetworkOk, &i.CreatedAt)
	return i, err
}
