// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"context"
)

const createDevice = `
INSERT INTO devices (user_id, name)
VALUES ($1, $2)
RETURNING id, user_id, name, is_active, created_at
`

type CreateDeviceParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice, arg.UserID, arg.Name)
	var i Device
	err := row.Scan(&i.ID, &i.UserID, &i.Name, &i.IsActive, &i.CreatedAt)
	return i, err
}

const listDevicesByUser = `
SELECT id, user_id, name, is_active, created_at FROM devices WHERE user_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListDevicesByUser(ctx context.Context, userID string) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(&i.ID, &i.UserID, &i.Name, &i.IsActive, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getDevice = `
SELECT id, user_id, name, is_active, created_at FROM devices WHERE id = $1 AND user_id = $2 LIMIT 1
`

func (q *Queries) GetDevice(ctx context.Context, id, userID string) (Device, error) {
	row := q.db.QueryRow(ctx, getDevice, id, userID)
	var i Device
	err := row.Scan(&i.ID, &i.UserID, &i.Name, &i.IsActive, &i.CreatedAt)
	return i, err
}

const deleteDevice = `
DELETE FROM devices WHERE id = $1 AND user_id = $2
`

func (q *Queries) DeleteDevice(ctx context.Context, id, userID string) error {
	_, err := q.db.Exec(ctx, deleteDevice, id, userID)
	return err
}

const countDevicesByUser = `
SELECT COUNT(*) FROM devices WHERE user_id = $1
`

func (q *Queries) CountDevicesByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countDevicesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
