// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device.sql

package repository

import (
	"context"
)

const countDevicesByUser = `-- name: CountDevicesByUser :one
SELECT COUNT(*) FROM devices WHERE user_id = $1
`

func (q *Queries) CountDevicesByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countDevicesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (user_id, name, api_key)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, is_active, created_at, api_key
`

type CreateDeviceParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
	APIKey string `json:"api_key"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice, arg.UserID, arg.Name, arg.APIKey)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.APIKey,
	)
	return i, err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices WHERE id = $1 AND user_id = $2
`

type DeleteDeviceParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteDevice(ctx context.Context, arg DeleteDeviceParams) error {
	_, err := q.db.Exec(ctx, deleteDevice, arg.ID, arg.UserID)
	return err
}

const getDevice = `-- name: GetDevice :one
SELECT id, user_id, name, is_active, created_at, api_key FROM devices WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetDeviceParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetDevice(ctx context.Context, arg GetDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, getDevice, arg.ID, arg.UserID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.APIKey,
	)
	return i, err
}

const getDeviceByAPIKey = `-- name: GetDeviceByAPIKey :one
SELECT id, user_id, name, is_active, created_at, api_key FROM devices WHERE api_key = $1 LIMIT 1
`

func (q *Queries) GetDeviceByAPIKey(ctx context.Context, apiKey string) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByAPIKey, apiKey)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.APIKey,
	)
	return i, err
}

const listDevicesByUser = `-- name: ListDevicesByUser :many
SELECT id, user_id, name, is_active, created_at, api_key FROM devices WHERE user_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListDevicesByUser(ctx context.Context, userID string) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
			&i.APIKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
