// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"context"
	"time"
)

type EmbeddedUser struct {
	UserID        string    `json:"user_id"`
	Name          string    `json:"name"`
	GuardianName  string    `json:"guardian_name"`
	GuardianPhone string    `json:"guardian_phone"`
	DeviceID      string    `json:"device_id"`
	CreatedAt     time.Time `json:"created_at"`
}

type CreateEmbeddedUserParams struct {
	UserID        string `json:"user_id"`
	Name          string `json:"name"`
	GuardianName  string `json:"guardian_name"`
	GuardianPhone string `json:"guardian_phone"`
	DeviceID      string `json:"device_id"`
}

const createEmbeddedUser = `
INSERT INTO embedded_users (user_id, name, guardian_name, guardian_phone, device_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING user_id, name, guardian_name, guardian_phone, device_id, created_at
`

func (q *Queries) CreateEmbeddedUser(ctx context.Context, arg CreateEmbeddedUserParams) (EmbeddedUser, error) {
	row := q.db.QueryRow(ctx, createEmbeddedUser, arg.UserID, arg.Name, arg.GuardianName, arg.GuardianPhone, arg.DeviceID)
	var i EmbeddedUser
	err := row.Scan(&i.UserID, &i.Name, &i.GuardianName, &i.GuardianPhone, &i.DeviceID, &i.CreatedAt)
	return i, err
}

const getEmbeddedUserByID = `
SELECT user_id, name, guardian_name, guardian_phone, device_id, created_at FROM embedded_users WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetEmbeddedUserByID(ctx context.Context, userID string) (EmbeddedUser, error) {
	row := q.db.QueryRow(ctx, getEmbeddedUserByID, userID)
	var i EmbeddedUser
	err := row.Scan(&i.UserID, &i.Name, &i.GuardianName, &i.GuardianPhone, &i.DeviceID, &i.CreatedAt)
	return i, err
}

const getEmbeddedUserByDeviceID = `
SELECT user_id, name, guardian_name, guardian_phone, device_id, created_at FROM embedded_users WHERE device_id = $1 LIMIT 1
`

func (q *Queries) GetEmbeddedUserByDeviceID(ctx context.Context, deviceID string) (EmbeddedUser, error) {
	row := q.db.QueryRow(ctx, getEmbeddedUserByDeviceID, deviceID)
	var i EmbeddedUser
	err := row.Scan(&i.UserID, &i.Name, &i.GuardianName, &i.GuardianPhone, &i.DeviceID, &i.CreatedAt)
	return i, err
}
