// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guardian.sql

package repository

import (
	"context"
)

const countGuardiansByUser = `-- name: CountGuardiansByUser :one
SELECT COUNT(*) FROM guardians WHERE user_id = $1
`

func (q *Queries) CountGuardiansByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countGuardiansByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGuardian = `-- name: CreateGuardian :one
INSERT INTO guardians (user_id, name, phone)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, phone, created_at
`

type CreateGuardianParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
	Phone  string `json:"phone"`
}

func (q *Queries) CreateGuardian(ctx context.Context, arg CreateGuardianParams) (Guardian, error) {
	row := q.db.QueryRow(ctx, createGuardian, arg.UserID, arg.Name, arg.Phone)
	var i Guardian
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Phone,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGuardian = `-- name: DeleteGuardian :exec
DELETE FROM guardians WHERE id = $1 AND user_id = $2
`

type DeleteGuardianParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteGuardian(ctx context.Context, arg DeleteGuardianParams) error {
	_, err := q.db.Exec(ctx, deleteGuardian, arg.ID, arg.UserID)
	return err
}

const getGuardian = `-- name: GetGuardian :one
SELECT id, user_id, name, phone, created_at FROM guardians WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetGuardianParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetGuardian(ctx context.Context, arg GetGuardianParams) (Guardian, error) {
	row := q.db.QueryRow(ctx, getGuardian, arg.ID, arg.UserID)
	var i Guardian
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Phone,
		&i.CreatedAt,
	)
	return i, err
}

const listGuardiansByUser = `-- name: ListGuardiansByUser :many
SELECT id, user_id, name, phone, created_at FROM guardians WHERE user_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListGuardiansByUser(ctx context.Context, userID string) ([]Guardian, error) {
	rows, err := q.db.Query(ctx, listGuardiansByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Guardian
	for rows.Next() {
		var i Guardian
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Phone,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
