// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"context"
)

const createGuardian = `
INSERT INTO guardians (user_id, name, phone)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, phone, created_at
`

type CreateGuardianParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
	Phone  string `json:"phone"`
}

func (q *Queries) CreateGuardian(ctx context.Context, arg CreateGuardianParams) (Guardian, error) {
	row := q.db.QueryRow(ctx, createGuardian, arg.UserID, arg.Name, arg.Phone)
	var i Guardian
	err := row.Scan(&i.ID, &i.UserID, &i.Name, &i.Phone, &i.CreatedAt)
	return i, err
}

const listGuardiansByUser = `
SELECT id, user_id, name, phone, created_at FROM guardians WHERE user_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListGuardiansByUser(ctx context.Context, userID string) ([]Guardian, error) {
	rows, err := q.db.Query(ctx, listGuardiansByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Guardian
	for rows.Next() {
		var i Guardian
		if err := rows.Scan(&i.ID, &i.UserID, &i.Name, &i.Phone, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getGuardian = `
SELECT id, user_id, name, phone, created_at FROM guardians WHERE id = $1 AND user_id = $2 LIMIT 1
`

func (q *Queries) GetGuardian(ctx context.Context, id, userID string) (Guardian, error) {
	row := q.db.QueryRow(ctx, getGuardian, id, userID)
	var i Guardian
	err := row.Scan(&i.ID, &i.UserID, &i.Name, &i.Phone, &i.CreatedAt)
	return i, err
}

const deleteGuardian = `
DELETE FROM guardians WHERE id = $1 AND user_id = $2
`

func (q *Queries) DeleteGuardian(ctx context.Context, id, userID string) error {
	_, err := q.db.Exec(ctx, deleteGuardian, id, userID)
	return err
}

const countGuardiansByUser = `
SELECT COUNT(*) FROM guardians WHERE user_id = $1
`

func (q *Queries) CountGuardiansByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countGuardiansByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
