// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"context"
	"time"
)

type Location struct {
	ID         string    `json:"id"`
	UserID     string    `json:"user_id"`
	DeviceID   string    `json:"device_id"`
	Latitude   float64   `json:"latitude"`
	Longitude  float64   `json:"longitude"`
	RecordedAt time.Time `json:"recorded_at"`
	CreatedAt  time.Time `json:"created_at"`
}

type CreateLocationParams struct {
	UserID     string    `json:"user_id"`
	DeviceID   string    `json:"device_id"`
	Latitude   float64   `json:"latitude"`
	Longitude  float64   `json:"longitude"`
	RecordedAt time.Time `json:"recorded_at"`
}

const createLocation = `
INSERT INTO locations (user_id, device_id, latitude, longitude, recorded_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, device_id, latitude, longitude, recorded_at, created_at
`

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation, arg.UserID, arg.DeviceID, arg.Latitude, arg.Longitude, arg.RecordedAt)
	var i Location
	err := row.Scan(&i.ID, &i.UserID, &i.DeviceID, &i.Latitude, &i.Longitude, &i.RecordedAt, &i.CreatedAt)
	return i, err
}
