// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Destination struct {
	ID         string    `json:"id"`
	UserID     string    `json:"user_id"`
	Name       string    `json:"name"`
	Latitude   float64   `json:"latitude"`
	Longitude  float64   `json:"longitude"`
	RadiusM    int32     `json:"radius_m"`
	TargetText string    `json:"target_text"`
	CreatedAt  time.Time `json:"created_at"`
}

type Device struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Name      string    `json:"name"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	APIKey    string    `json:"api_key"`
}

type DeviceStatus struct {
	ID        string    `json:"id"`
	DeviceID  string    `json:"device_id"`
	Battery   int32     `json:"battery"`
	LidarOk   bool      `json:"lidar_ok"`
	CameraOk  bool      `json:"camera_ok"`
	GpsOk     bool      `json:"gps_ok"`
	NetworkOk bool      `json:"network_ok"`
	CreatedAt time.Time `json:"created_at"`
}

type EmbeddedUser struct {
	UserID        string    `json:"user_id"`
	Name          string    `json:"name"`
	GuardianName  string    `json:"guardian_name"`
	GuardianPhone string    `json:"guardian_phone"`
	DeviceID      string    `json:"device_id"`
	CreatedAt     time.Time `json:"created_at"`
}

type Guardian struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Name      string    `json:"name"`
	Phone     string    `json:"phone"`
	CreatedAt time.Time `json:"created_at"`
}

type Location struct {
	ID         string    `json:"id"`
	UserID     string    `json:"user_id"`
	DeviceID   string    `json:"device_id"`
	Latitude   float64   `json:"latitude"`
	Longitude  float64   `json:"longitude"`
	RecordedAt time.Time `json:"recorded_at"`
	CreatedAt  time.Time `json:"created_at"`
}

type NavigationInstruction struct {
	ID             string      `json:"id"`
	SessionID      string      `json:"session_id"`
	Action         string      `json:"action"`
	DistanceMeters pgtype.Int4 `json:"distance_meters"`
	Message        pgtype.Text `json:"message"`
	CreatedAt      time.Time   `json:"created_at"`
}

type NavigationSession struct {
	ID             string        `json:"id"`
	UserID         string        `json:"user_id"`
	DeviceID       *string       `json:"device_id"`
	DestinationID  string        `json:"destination_id"`
	Status         string        `json:"status"`
	StartLatitude  pgtype.Float8 `json:"start_latitude"`
	StartLongitude pgtype.Float8 `json:"start_longitude"`
	CreatedAt      time.Time     `json:"created_at"`
	UpdatedAt      time.Time     `json:"updated_at"`
}

type OcrLog struct {
	ID             string    `json:"id"`
	DestinationID  string    `json:"destination_id"`
	RecognizedText string    `json:"recognized_text"`
	TargetText     string    `json:"target_text"`
	Matched        bool      `json:"matched"`
	Confidence     float32   `json:"confidence"`
	CreatedAt      time.Time `json:"created_at"`
}

type SosEvent struct {
	ID             string      `json:"id"`
	UserID         string      `json:"user_id"`
	DeviceID       string      `json:"device_id"`
	EventType      string      `json:"event_type"`
	Latitude       float64     `json:"latitude"`
	Longitude      float64     `json:"longitude"`
	CreatedAt      time.Time   `json:"created_at"`
	Battery        pgtype.Int4 `json:"battery"`
	SentToGuardian bool        `json:"sent_to_guardian"`
}

type User struct {
	ID            string    `json:"id"`
	Email         string    `json:"email"`
	Nickname      string    `json:"nickname"`
	PasswordHash  *string   `json:"password_hash"`
	EmailVerified bool      `json:"email_verified"`
	CreatedAt     time.Time `json:"created_at"`
}
