// Code generated by sqlc. DO NOT EDIT.

package repository

import "time"

type User struct {
	ID            string    `json:"id"`
	Email         string    `json:"email"`
	Nickname      string    `json:"nickname"`
	PasswordHash  *string   `json:"password_hash"`
	EmailVerified bool      `json:"email_verified"`
	CreatedAt     time.Time `json:"created_at"`
}

type Device struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Name      string    `json:"name"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
}

type Guardian struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Name      string    `json:"name"`
	Phone     string    `json:"phone"`
	CreatedAt time.Time `json:"created_at"`
}

type Destination struct {
	ID         string    `json:"id"`
	UserID     string    `json:"user_id"`
	Name       string    `json:"name"`
	Latitude   float64   `json:"latitude"`
	Longitude  float64   `json:"longitude"`
	RadiusM    int32     `json:"radius_m"`
	TargetText string    `json:"target_text"`
	CreatedAt  time.Time `json:"created_at"`
}

type SosEvent struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	DeviceID  string    `json:"device_id"`
	EventType string    `json:"event_type"`
	Latitude  float64   `json:"latitude"`
	Longitude float64   `json:"longitude"`
	CreatedAt time.Time `json:"created_at"`
}

type OcrLog struct {
	ID             string    `json:"id"`
	DestinationID  string    `json:"destination_id"`
	RecognizedText string    `json:"recognized_text"`
	TargetText     string    `json:"target_text"`
	Matched        bool      `json:"matched"`
	Confidence     float32   `json:"confidence"`
	CreatedAt      time.Time `json:"created_at"`
}
