// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: navigation.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNavigationInstruction = `-- name: CreateNavigationInstruction :one
INSERT INTO navigation_instructions (session_id, action, distance_meters, message)
VALUES ($1, $2, $3, $4)
RETURNING id, session_id, action, distance_meters, message, created_at
`

type CreateNavigationInstructionParams struct {
	SessionID      string      `json:"session_id"`
	Action         string      `json:"action"`
	DistanceMeters pgtype.Int4 `json:"distance_meters"`
	Message        pgtype.Text `json:"message"`
}

func (q *Queries) CreateNavigationInstruction(ctx context.Context, arg CreateNavigationInstructionParams) (NavigationInstruction, error) {
	row := q.db.QueryRow(ctx, createNavigationInstruction,
		arg.SessionID,
		arg.Action,
		arg.DistanceMeters,
		arg.Message,
	)
	var i NavigationInstruction
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Action,
		&i.DistanceMeters,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const createNavigationSession = `-- name: CreateNavigationSession :one
INSERT INTO navigation_sessions (user_id, device_id, destination_id, start_latitude, start_longitude)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, device_id, destination_id, status, start_latitude, start_longitude, created_at, updated_at
`

type CreateNavigationSessionParams struct {
	UserID         string        `json:"user_id"`
	DeviceID       *string       `json:"device_id"`
	DestinationID  string        `json:"destination_id"`
	StartLatitude  pgtype.Float8 `json:"start_latitude"`
	StartLongitude pgtype.Float8 `json:"start_longitude"`
}

func (q *Queries) CreateNavigationSession(ctx context.Context, arg CreateNavigationSessionParams) (NavigationSession, error) {
	row := q.db.QueryRow(ctx, createNavigationSession,
		arg.UserID,
		arg.DeviceID,
		arg.DestinationID,
		arg.StartLatitude,
		arg.StartLongitude,
	)
	var i NavigationSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.DestinationID,
		&i.Status,
		&i.StartLatitude,
		&i.StartLongitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestNavigationInstruction = `-- name: GetLatestNavigationInstruction :one
SELECT id, session_id, action, distance_meters, message, created_at FROM navigation_instructions
WHERE session_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestNavigationInstruction(ctx context.Context, sessionID string) (NavigationInstruction, error) {
	row := q.db.QueryRow(ctx, getLatestNavigationInstruction, sessionID)
	var i NavigationInstruction
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Action,
		&i.DistanceMeters,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const getNavigationSession = `-- name: GetNavigationSession :one
SELECT id, user_id, device_id, destination_id, status, start_latitude, start_longitude, created_at, updated_at FROM navigation_sessions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetNavigationSession(ctx context.Context, id string) (NavigationSession, error) {
	row := q.db.QueryRow(ctx, getNavigationSession, id)
	var i NavigationSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.DestinationID,
		&i.Status,
		&i.StartLatitude,
		&i.StartLongitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNavigationSessionStatus = `-- name: UpdateNavigationSessionStatus :one
UPDATE navigation_sessions
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, device_id, destination_id, status, start_latitude, start_longitude, created_at, updated_at
`

type UpdateNavigationSessionStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateNavigationSessionStatus(ctx context.Context, arg UpdateNavigationSessionStatusParams) (NavigationSession, error) {
	row := q.db.QueryRow(ctx, updateNavigationSessionStatus, arg.ID, arg.Status)
	var i NavigationSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.DestinationID,
		&i.Status,
		&i.StartLatitude,
		&i.StartLongitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
