// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"context"
)

const createOcrLog = `
INSERT INTO ocr_logs (destination_id, recognized_text, target_text, matched, confidence)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, destination_id, recognized_text, target_text, matched, confidence, created_at
`

type CreateOcrLogParams struct {
	DestinationID  string  `json:"destination_id"`
	RecognizedText string  `json:"recognized_text"`
	TargetText     string  `json:"target_text"`
	Matched        bool    `json:"matched"`
	Confidence     float32 `json:"confidence"`
}

func (q *Queries) CreateOcrLog(ctx context.Context, arg CreateOcrLogParams) (OcrLog, error) {
	row := q.db.QueryRow(ctx, createOcrLog,
		arg.DestinationID, arg.RecognizedText, arg.TargetText, arg.Matched, arg.Confidence,
	)
	var i OcrLog
	err := row.Scan(&i.ID, &i.DestinationID, &i.RecognizedText, &i.TargetText, &i.Matched, &i.Confidence, &i.CreatedAt)
	return i, err
}
