// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sos.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSosEvent = `-- name: CreateSosEvent :one
INSERT INTO sos_events (user_id, device_id, event_type, latitude, longitude, battery)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, device_id, event_type, latitude, longitude, created_at, battery, sent_to_guardian
`

type CreateSosEventParams struct {
	UserID    string      `json:"user_id"`
	DeviceID  string      `json:"device_id"`
	EventType string      `json:"event_type"`
	Latitude  float64     `json:"latitude"`
	Longitude float64     `json:"longitude"`
	Battery   pgtype.Int4 `json:"battery"`
}

func (q *Queries) CreateSosEvent(ctx context.Context, arg CreateSosEventParams) (SosEvent, error) {
	row := q.db.QueryRow(ctx, createSosEvent,
		arg.UserID,
		arg.DeviceID,
		arg.EventType,
		arg.Latitude,
		arg.Longitude,
		arg.Battery,
	)
	var i SosEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.EventType,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.Battery,
		&i.SentToGuardian,
	)
	return i, err
}

const listSosEventsByUser = `-- name: ListSosEventsByUser :many
SELECT id, user_id, device_id, event_type, latitude, longitude, created_at, battery, sent_to_guardian FROM sos_events WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSosEventsByUser(ctx context.Context, userID string) ([]SosEvent, error) {
	rows, err := q.db.Query(ctx, listSosEventsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SosEvent
	for rows.Next() {
		var i SosEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceID,
			&i.EventType,
			&i.Latitude,
			&i.Longitude,
			&i.CreatedAt,
			&i.Battery,
			&i.SentToGuardian,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
