// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"context"
)

const createSosEvent = `
INSERT INTO sos_events (user_id, device_id, event_type, latitude, longitude)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, device_id, event_type, latitude, longitude, created_at
`

type CreateSosEventParams struct {
	UserID    string  `json:"user_id"`
	DeviceID  string  `json:"device_id"`
	EventType string  `json:"event_type"`
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

func (q *Queries) CreateSosEvent(ctx context.Context, arg CreateSosEventParams) (SosEvent, error) {
	row := q.db.QueryRow(ctx, createSosEvent,
		arg.UserID, arg.DeviceID, arg.EventType, arg.Latitude, arg.Longitude,
	)
	var i SosEvent
	err := row.Scan(&i.ID, &i.UserID, &i.DeviceID, &i.EventType, &i.Latitude, &i.Longitude, &i.CreatedAt)
	return i, err
}

const listSosEventsByUser = `
SELECT id, user_id, device_id, event_type, latitude, longitude, created_at
FROM sos_events WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSosEventsByUser(ctx context.Context, userID string) ([]SosEvent, error) {
	rows, err := q.db.Query(ctx, listSosEventsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SosEvent
	for rows.Next() {
		var i SosEvent
		if err := rows.Scan(&i.ID, &i.UserID, &i.DeviceID, &i.EventType, &i.Latitude, &i.Longitude, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}
