// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"context"
)

const createUser = `
INSERT INTO users (email, nickname, password_hash, email_verified)
VALUES ($1, $2, $3, $4)
RETURNING id, email, nickname, password_hash, email_verified, created_at
`

type CreateUserParams struct {
	Email         string  `json:"email"`
	Nickname      string  `json:"nickname"`
	PasswordHash  *string `json:"password_hash"`
	EmailVerified bool    `json:"email_verified"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Nickname, arg.PasswordHash, arg.EmailVerified)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.Nickname, &i.PasswordHash, &i.EmailVerified, &i.CreatedAt)
	return i, err
}

const getUserByEmail = `
SELECT id, email, nickname, password_hash, email_verified, created_at FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.Nickname, &i.PasswordHash, &i.EmailVerified, &i.CreatedAt)
	return i, err
}

const getUserByID = `
SELECT id, email, nickname, password_hash, email_verified, created_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.Nickname, &i.PasswordHash, &i.EmailVerified, &i.CreatedAt)
	return i, err
}

const updateEmailVerified = `
UPDATE users SET email_verified = $1 WHERE email = $2
`

func (q *Queries) UpdateEmailVerified(ctx context.Context, verified bool, email string) error {
	_, err := q.db.Exec(ctx, updateEmailVerified, verified, email)
	return err
}
